#!/bin/ksh
#-----------------------------------------------------------------------
# (C) COPYRIGHT International Business Machines Corp. 1996
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# NAME:     db2rstar
#
# FUNCTION: This script calls the remote db2start command for
#           Bourne shell or Korn shell users.
#
# USAGE:    . db2rstar <profile_name>
#           profile_name: profile name located in the $HOME/sqllib directory
#
#           This script can be invoked only by the db2start command
#           is for internal usage only.
#-----------------------------------------------------------------------
export DB2REMOTE=start

#Get the fully qualified name for the $HOME/sqllib path
path=${0%/*/*}

#execute the profile
. $path/$1
shift

cmd=$1
shift

#execute the local db2start or db2castart
$HOME/sqllib/adm/$cmd NOMSG REMOTE "$@"

