#!/bin/ksh
#-----------------------------------------------------------------------
# (C) COPYRIGHT International Business Machines Corp. 1996
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# NAME:     db2rstar
#
# FUNCTION: This script calls the remote db2stop command for
#           Bourne shell or Korn shell users.
#
# USAGE:    . db2rstop <profile_name>
#           profile_name: profile name located in the $HOME/sqllib directory
#
#           This script can be invoked only by the db2stop command
#           is for internal usage only.
#-----------------------------------------------------------------------
export DB2REMOTE=stop

#Get the fully qualified name for the $HOME/sqllib path
path=${0%/*/*}

#execute the profile
. $path/$1
shift

cmd=$1
shift

# check if environment has memory protection enabled
protect_env=
unix_type=`uname`

if [[ "$unix_type" = "AIX" ]]
then
   db2env=`db2set`
   doiprotect=`echo "$db2env" | sed -n -e 's/.*\(DB2MEMDBG=[a-zA-Z0-9_]*\).*/\1/gp'`
   if [[ -n "$doiprotect" ]]
   then
     protect_env='/bin/env MPROTECT_SHM=ON LDR_CNTRL=DATAPSIZE=4K '
   fi
fi

   #execute the local db2stop or db2castop
   $protect_env $HOME/sqllib/adm/$cmd NOMSG REMOTE "$@"

