#!/bin/ksh
#-----------------------------------------------------------------------
# (C) COPYRIGHT International Business Machines Corp. 1996
# All Rights Reserved
# Licensed Materials - Property of IBM
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
# NAME:     db2rem
#
# FUNCTION: This script calls the remote db2remot command for
#           Bourne shell or Korn shell users.
#
# USAGE:    . db2rem <profile_name>
#           profile_name: profile name located in the $HOME/sqllib directory
#
#           This script is for internal usage only.
#-----------------------------------------------------------------------

#Get the fully qualified name for the $HOME/sqllib path
path=${0%/*/*}

#execute the profile
. $path/$1

#execute the local db2remot
$HOME/sqllib/adm/db2remot "$@"
