apiVersion: eventstreams.ibm.com/v1beta1
kind: EventStreams
metadata:
  name: light-es
  namespace: eventstreams
spec:
  security:
    internalTls: TLSv1.2
  adminApi: {}
  adminUI: {}
  collector: {}
  license:
    accept: true
    use: CloudPakForIntegrationProduction
  restProducer: {}
  schemaRegistry:
    storage:
      type: ephemeral
  strimziOverrides:
    kafka:
      authorization:
        type: runas
      config:
        inter.broker.protocol.version: '2.6'
        interceptor.class.names: com.ibm.eventstreams.interceptors.metrics.ProducerMetricsInterceptor
        log.message.format.version: '2.6'
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
      listeners:
        external:
          authentication:
            type: scram-sha-512
          type: route
        tls:
          authentication:
            type: tls
      metrics: {}
      replicas: 3
      storage:
        class: ibmc-block-gold
        size: 20Gi
        type: persistent-claim
    zookeeper:
      metrics: {}
      replicas: 3
      storage:
        class: ibmc-block-gold
        size: 5Gi
        type: persistent-claim
  version: 10.1.0

