version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit-user
      RABBITMQ_DEFAULT_PASS: rabbit-pass
    volumes:
      - ./enable_plugins:/etc/rabbitmq/enabled_plugins
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.6.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - LOG_DIR=/tmp/logs
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
  kafka:
    image: strimzi/kafka:latest-kafka-2.6.0
    command: [
    "sh", "-c",
    "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG_DIR: /tmp/logs
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home          
    depends_on:
    - zookeeper
  kconnect:
    image: ibmcase/kconnect:0.1.0
    ports:
      - '8083:8083'
    depends_on: 
      - kafka
  db2:
    container_name: db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: ${DB2INST1_PASSWORD:-db2inst1}
    image: ibmcom/db2:11.5.0.0a
    ports:
        - 50000:50000
    privileged: true
    volumes:
        - ./data/db2data:/database
  simulator:
    image: ibmcase/eda-store-simulator
    depends_on:
      - kafka
    hostname: storeapp
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_TARGET_MESSAGING: RabbitMQ,Kafka,IBMMQ
      AMQP_USERNAME: rabbit-user
      AMQP_PASSWORD: rabbit-pass
      AMQP_HOST: rabbitmq
      MQ_HOST: ibmmq
    depends_on:
      - kafka
      - ibmmq
      - rabbitmq
  iteminventory:
    image: ibmcase/item-aggregator:0.0.6
    ports:
      - 8081:8080
    environment: 
        KAFKA_BROKERS: kafka:9092
        SECURE_PROTOCOL: PLAINTEXT
        KAFKA_STREAMS_SASL_MECHANISM: ''
        USER_CERT_PWD: ''
        USER_CERT_PATH: ''
        KAFKA_CERT_PATH: ''
        KAFKA_CERT_PWD: ''
    depends_on:
      - kafka
  ibmmq:
    image: ibmcom/mq
    ports:
        - '1414:1414'
        - '9443:9443'
        - '9157:9157'
    volumes:
        - qm1data:/mnt/mqm
    stdin_open: true
    tty: true
    restart: always
    environment:
        LICENSE: accept
        MQ_QMGR_NAME: QM1
        MQ_APP_PASSWORD: passw0rd
        MQ_ENABLE_METRICS: "true"
volumes:
  qm1data:
