version: '3.7'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbit-user
      RABBITMQ_DEFAULT_PASS: rabbit-pass
    volumes:
      - ./enable_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - kafka-network
  zookeeper:
    image: strimzi/kafka:latest-kafka-2.6.0
    hostname: zookeeper
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      - ZOO_MY_ID=1
      - ZOO_PORT=2181
      - ZOO_SERVERS=server.1=zookeeper:2888:3888
      - ALLOW_ANONYMOUS_LOGIN=yes
      - LOG_DIR=/tmp/logs
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
    networks:
      - kafka-network
  kafka:
    image: strimzi/kafka:latest-kafka-2.6.0
    hostname: kafka
    command: [
    "sh", "-c",
    "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    ports:
        - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG_DIR: /tmp/logs
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/home          
    depends_on:
    - zookeeper
    networks:
      - kafka-network
  simulator:
    image: ibmcase/eda-store-simulator
    depends_on:
      - kafka
    hostname: storeapp
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_TARGET_MESSAGING: RabbitMQ,Kafka,IBMMQ
      AMQP_USERNAME: rabbit-user
      AMQP_PASSWORD: rabbit-pass
      AMQP_HOST: rabbitmq
      MQ_HOST: ibmmq
    depends_on:
      - kafka
      - ibmmq
      - rabbitmq
    networks:
      - kafka-network
  ibmmq:
    image: ibmcom/mq
    ports:
        - '1414:1414'
        - '9443:9443'
        - '9157:9157'
    volumes:
        - qm1data:/mnt/mqm
    stdin_open: true
    tty: true
    restart: always
    environment:
        LICENSE: accept
        MQ_QMGR_NAME: QM1
        MQ_APP_PASSWORD: passw0rd
        MQ_ENABLE_METRICS: "true"
    networks:
      - kafka-network
volumes:
  qm1data:
networks:
  kafka-network:
    name: kafkanet