apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-cluster
  annotations:
    openshift.io/sa.scc.supplemental-groups: 999/1
    openshift.io/sa.scc.uid-range: 999/1
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmqcluster
  namespace:  rabbitmq-cluster
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_amqp1_0
      - rabbitmq_management
      - rabbitmq_web_dispatch
      - rabbitmq_management_agent
    