apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmqcluster
  namespace:  rabbitmq-cluster
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_amqp1_0
      - rabbitmq_management
      - rabbitmq_web_dispatch
      - rabbitmq_management_agent
    