---
version: '2'
services:
    zookeeper:
        image: strimzi/kafka:latest-kafka-2.5.0
        command: [
          "sh", "-c",
          "bin/zookeeper-server-start.sh config/zookeeper.properties"
        ]
        ports:
          - "2181:2181"
        environment:
          LOG_DIR: /tmp/logs
    
    kafka:
        image: strimzi/kafka:latest-kafka-2.5.0
        command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
        ]
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            LOG_DIR: "/tmp/logs"
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            
    ksqldb-server:
        image: confluentinc/ksqldb-server:0.11.0
        hostname: ksqldb-server
        container_name: ksqldb-server
        depends_on:
            - kafka
        ports:
            - "8088:8088"
        environment:
            KSQL_LISTENERS: http://0.0.0.0:8088
            KSQL_BOOTSTRAP_SERVERS: kafka:9092
            KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
            KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"

    ksqldb-cli:
        image: confluentinc/ksqldb-cli:0.11.0
        container_name: ksqldb-cli
        depends_on:
            - kafka
            - ksqldb-server
        entrypoint: /bin/sh
        tty: true
networks:
    default:
        external:
            name: kafkanet